server:
  port: 8009


spring:
  main:
    web-application-type: reactive
  application:
    name: light-reading-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

zuul:
  routes:
    book:
      path: /book/**
      serviceId: lightreadingcloudbook

    account:
      path: /account/**
      serviceId: light-reading-cloud-account

    homepage:
      path: /index/**
      serviceId: light-reading-cloud-homepage



eureka:
  instance:
    # 注册服务的IP，而不是逻辑名称
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
    register-with-eureka: true
    fetch-registry: true

hystrix:
  threadpool:
    default:
      coreSize: 20 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数，默认值-1
      queueSizeRejectionThreshold: 400
