
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zealon159/config-repo
          search-paths: dev,qa
      name: light-reading-cloud-config

server:
  port: 8888